name = "jacob"
license = "MIT"
licenselink = "https://github.com/jacobmillward/custom-hugo-theme-m10c/blob/master/LICENSE.md"
description = "Custom theme based on m10c (https://github.com/vaga/hugo-theme-m10c)"
homepage = "https://github.com/jacobmillward/custom-hugo-theme-m10c"
tags = ["blog", "minimalistic", "minimal", "responsive", "dark"]
features = [
  "minimalistic blog",
  "social icons",
  "editable colors"
]
min_version = 0.55

[author]
  name = "Jacob Millward"
  homepage = "https://jacob.millward.dev"

